14 create traps
In-Search-Of-Treasure/In-Search-Of-Treasure pull request #15
Opened 2022-05-15 02:37 UTC by Phnc

Solve issue #14

2022-05-15 15:44 UTC, hnmendes commented on Assets/Controllers/Player/MaksimController.cs
> +            if (collision.gameObject.GetComponent<Animator>().GetCurrentAnimatorStateInfo(0).IsName("Spike_Trap_Middle"))
Add a constant for this string.

2022-05-17 03:46 UTC, hnmendes requested changes
Please add the constant.

2022-05-21 22:02 UTC, Phnc commented on Assets/Controllers/Player/MaksimController.cs
> +            if (collision.gameObject.GetComponent<Animator>().GetCurrentAnimatorStateInfo(0).IsName("Spike_Trap_Middle"))
Resolved

2022-05-21 22:06 UTC, hnmendes approved these changes

2022-05-21 22:06 UTC, merged